import { copyFile, mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

/**
 * Stage the chess engine into `public/` so the static export serves it.
 *
 * The engine is a 7 MB WebAssembly binary. It is copied from the installed
 * package at build time rather than committed, which keeps the repository free
 * of large binaries while still producing a fully self-contained export.
 *
 * Build choice: `lite-single`.
 *
 * - `single` means single-threaded. Multi-threaded builds need SharedArrayBuffer,
 *   which requires COOP/COEP response headers that static hosting cannot set.
 *   See ADR 0002.
 * - `lite` means the smaller neural network. The full network is 107 MB, which
 *   exceeds GitHub's 100 MB per-file limit outright, and would be an
 *   unreasonable download for an offline-first application regardless.
 */
const require = createRequire(import.meta.url);
const packageRoot = dirname(require.resolve("stockfish/package.json"));

const OUTPUT_DIR = join(process.cwd(), "public", "engine");

const FILES = [
  "stockfish-18-lite-single.js",
  "stockfish-18-lite-single.wasm",
];

/**
 * Stockfish is GPL-3.0. The licence travels with the binary, so the notice is
 * written next to it rather than living only in the repository root.
 */
const NOTICE = `This directory contains Stockfish, compiled to WebAssembly.

Stockfish is free software distributed under the GNU General Public License
version 3. It is a separate program from ChessVault: it runs in its own worker
and communicates over the UCI text protocol.

Source: https://github.com/official-stockfish/Stockfish
WebAssembly build: https://github.com/nmrugg/stockfish.js
Licence: https://www.gnu.org/licenses/gpl-3.0.html

The files in this directory are generated by scripts/copy-engine.mjs and are not
tracked in version control.
`;

await mkdir(OUTPUT_DIR, { recursive: true });

for (const file of FILES) {
  await copyFile(join(packageRoot, "bin", file), join(OUTPUT_DIR, file));
}

await writeFile(join(OUTPUT_DIR, "README.txt"), NOTICE, "utf8");

console.log(`Staged engine into public/engine (${FILES.length} files).`);
